apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-user-role
rules:
  - verbs:
      - create
      - get
      - list
      - watch
      - delete
    apiGroups:
      - ''
    resources:
      - pods
      - configmaps
      - services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-user-role-binding
subjects:
  - kind: ServiceAccount
    name: spark-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-user-role
